baseURL = 'https://blog.kelpo.org/'
languageCode = 'en-us'
title = 'One Kelvin'
description = 'The Absolute Standard'
theme = 'mana'

[params]
  description = "The Absolute Standard"
  favicon = "/favicon/favicon.ico"
  footerText = "Built with Hugo and Mana theme"  # Optional

  # Hero section title (optional - defaults to site.Title)
  heroTitleLine1 = "One Kelvin"  # First line of hero title
  # heroTitleLine2 = "The Absolute Standard"    # Second line of hero title (optional)

[params.avatar]
url = "https://avatars.githubusercontent.com/u/1455743"

[params.social]
  github = "https://github.com/KelvinCoding"
  email = "me@kelvincoding.com"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
